name: Haber Botu Otomasyonu

on:
  schedule:
    - cron: '0 * * * *'  # Her saatin 0. dakikasında çalış
  workflow_dispatch:      # İstediğin zaman manuel çalıştırmak için

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Python Kurulumu
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Gerekli Kütüphaneleri Yükle
        run: pip install feedparser aiohttp firebase-admin
      - name: Botu Çalıştır
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: python bot.py
